### PR TITLE
initial changes to postgreSQRL access

### PR DESCRIPTION
**Pull request by jcolomb**
hey.
I had to make some code to access the flybase database, I thought I would add that to the rflybase package.
I have no experience in package making and the code will probably needs some tweaking before being ready for development... At least it works for now. I do not know if you have some interests in making rflybase alive again, but if yes, the access to the postgresql version of the database appears the nicer to me.

Happy coding.
Julien

### CODE REVIEW

**Comment by sckott** [comment]
thanks @jcolomb - i'll have a look and get back to you

**Comment by sckott** [comment]
- Make sure to run `devtools::document()` or simiilar in `roxygen2` package, or in the rstudio gui - to generate man files. Make sure to document all parameters, what the functions return, links to any resources online, etc. 
- Don't use collate in DESCRIPTION file, not needed, let me know if you think i'm wrong
- include some examples of use. I couldn't really test the code, as I don't know what a valid CG number is. 
- include some tests for the new function(S)
- change fxn names to be all lower case. starting with `fb_` is good though
- the fxn `FB_connect` should be changed to instead of putting `drv` and `con` in global environment, returning the `con` object from the function call, - this also means `FB_connect` should be exported (including fxn name change, see above). Since one can download and use the DB locally, should expose parameters for setting Postgres driver settings
- `DBI` is also a dep if using `RPostgreSQL` - add `DBI` to `imports`  - you also need to namespace your fxn calls to these packages, e.g., `DBI::dbConnect` instead of `dbConnect`

you can make changes and push them to `jcolomb/rflybase` - and they will appear here.

**Comment by jcolomb** [comment]
> On 17 Oct 2016, at 23:28, Scott Chamberlain notifications@github.com wrote:
> 
> Make sure to run devtools::document() or simiilar in roxygen2 package, or in the rstudio gui - to generate man files. Make sure to document all parameters, what the functions return, links to any resources online, etc. 
> Don't use collate in DESCRIPTION file, not needed, let me know if you think i'm wrong
> it was there before, I do not know how/if the flybasesymbol function is working. (I also do not know what collate means here)
> include some examples of use. I couldn't really test the code, as I don't know what a valid CG number is.
> done
> include some tests for the new function(S)
> I do not know what you mean with tests.
> change fxn names to be all lower case. starting with fb_ is good though
> done
> the fxn FB_connect should be changed to instead of putting drv and con in global environment, returning the con object from the function call, - this also means FB_connect should be exported (including fxn name change, see above). Since one can download and use the DB locally, should expose parameters for setting Postgres driver settings
> I can probably not solve this alone. It also gets problem when the connection is not use for some time: the connection is not working anymore, while the “con” value still exists. the second “if” was thought to get solve this, but it does not… 
> I am not sure how to return con from the function, if you try to reinitialise con each time, it stops at 16 use of the function (that is why I put them as global variables, that are updated only if non-existent). I changed the function a bit, but kept the global environment stuff, tell me if there is a way around.
> I am quite newbie here and I do not really understand what “exported” means. 

For the DB local, I have no clue what the settings change will be… I hoped you could help me with that ;).

> DBI is also a dep if using RPostgreSQL - add DBI to imports - you also need to namespace your fxn calls to these packages, e.g., DBI::dbConnect instead of dbConnect
> you can make changes and push them to jcolomb/rflybase - and they will appear here.
> 
> Done.

Sorry to be so inexperienced and make so many mistakes,
Best,
Julien

**Comment by sckott** [comment]
> it was there before, I do not know how/if the flybasesymbol function is working. (I also do not know what collate means here)

I can make this change after merging

> I do not know what you mean with tests.

i can add tests after merging

> I can probably not solve this alone. It also gets problem when the connection is not use for some time: the connection is not working anymore, while the “con” value still exists. the second “if” was thought to get solve this, but it does not… I am not sure how to return con from the function, if you try to reinitialise con each time, it stops at 16 use of the function (that is why I put them as global variables, that are updated only if non-existent). I changed the function a bit, but kept the global environment stuff, tell me if there is a way around.

I see the problem. I think it is okay to just document that users shouldn't create a whole bunch of connections, but rather just create 1 per R session. 

> I am quite newbie here and I do not really understand what “exported” means.

Just to use `@export` tag so it gets exported and available to the user

> For the DB local, I have no clue what the settings change will be… I hoped you could help me with that ;).

yes, I can help after merging

> Sorry to be so inexperienced and make so many mistakes,

no problem at all!

**Comment by sckott** [comment]
any updates on this @jcolomb ?

**Comment by jcolomb** [comment]
I thought I did everything you needed and you will do the rest after merging (?).

**Comment by sckott** [comment]
@jcolomb ah, correct, sorry about that!  

will do ...

**Pull request merged**
